default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: kintide_development

test:
  <<: *default
  database: kintide_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *primary_production
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
    migrations_paths: db/queue_migrate
