default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: kintide_development

test:
  <<: *default
  database: kintide_test

production:
  primary: &primary_production
    <<: *default
    database: kintide_production
    username: kintide
    password: <%= ENV['KINTIDE_DATABASE_PASSWORD'] %>
  queue:
    <<: *primary_production
    database: kintide_production_queue
    migrations_paths: db/queue_migrate
